language: node_js
node_js:
  - "7"

addons:
  firefox: "latest"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install

script:
  - npm run test -- --browsers Firefox --single-run
  - npm run lint
